import { BlueprintQuestion, FormatBlueprint } from "./types";

export const formatOptions: FormatBlueprint[] = [
  {
    id: "format-prototype",
    name: "Genetics Midterm Template",
    description:
      "Full cover sheet with structured sections ready for automated generation.",
    savedAt: "2 days ago",
    status: "Active",
    layout: {
      headerLines: [
        "XYZ University",
        "School of Magic",
        "Department of Magical Food",
        "Final Written Examination (1/2025)",
        "Undergraduate Program",
      ],
      metadata: [
        { label: "Course title", value: "ABC1234" },
        { label: "Lecturer", value: "Harry Potter" },
        { label: "Date", value: "10 June 2025" },
        { label: "Time", value: "09:00 AM - 12:00 PM" },
      ],
      instructionIntro:
        "This 6-page examination paper (including this page) consists of 2 parts:",
      instructions: [
        {
          text: "Answer the questions in the computerized answer sheet using '2B' pencil only.",
          emphasis: "normal",
        },
        {
          text: "Write your ID, name, and section number on the computerized answer sheet.",
          emphasis: "underline",
        },
        {
          text:
            "Do not forget to blacken your ID, subject code, and your section number on the answer sheet.",
          emphasis: "bold",
        },
        {
          text:
            "Avoid academic cheating by not taking any part of the exam paper out of the examination room.",
          emphasis: "normal",
        },
      ],
      candidateFields: [
        "Name: _________________________________",
        "ID: _____________________",
        "Section: ______________",
      ],
      footerNotes: ["Total 18 marks equivalent to 100%"],
    },
    sections: [
      {
        name: "Section A: Multiple Choice",
        questionType: "Multiple Choice",
        questions: 30,
        difficulty: "Foundational",
        category: "Foundations",
      },
      {
        name: "Section B: Short Answers",
        questionType: "Short Answer",
        questions: 15,
        difficulty: "Core",
        category: "Processes",
      },
      {
        name: "Section C: Essay",
        questionType: "Long Form",
        questions: 3,
        difficulty: "Applied",
        category: "Synthesis",
      },
    ],
    generationSettings: [
      { label: "Questions to generate", value: "15" },
      { label: "Difficulty mix", value: "40% Easy · 40% Medium · 20% Hard" },
      { label: "Bloom levels", value: "Remember · Apply · Analyze" },
      { label: "Language", value: "English (US)" },
    ],
  },
  {
    id: "format-drafting",
    name: "Econometrics Final v1",
    description:
      "Draft pulled from last semester. Needs instruction rewrite before export.",
    savedAt: "5 days ago",
    status: "Draft",
    layout: {
      headerLines: [
        "Evergreen University",
        "Faculty of Economics",
        "Econometrics Final Examination",
        "Semester 1 / 2025",
        "Undergraduate Program",
      ],
      metadata: [
        { label: "Course title", value: "ECON3421" },
        { label: "Lecturer", value: "Prof. Linh Tran" },
        { label: "Date", value: "24 May 2025" },
        { label: "Location", value: "Hall B" },
      ],
      instructionIntro:
        "This assessment includes both structured response and analytical essays:",
      instructions: [
        {
          text: "Show full working for each quantitative answer.",
          emphasis: "bold",
        },
        {
          text: "Round numerical responses to two decimal places unless specified.",
          emphasis: "normal",
        },
        {
          text: "Submit all rough work with your script before leaving the room.",
          emphasis: "underline",
        },
      ],
      candidateFields: [
        "Candidate name: _________________________________",
        "Student ID: _____________________",
        "Program: ______________",
      ],
      footerNotes: ["Calculator policy: Non-programmable only."],
    },
    sections: [
      {
        name: "Part I: Multiple Choice",
        questionType: "Multiple Choice",
        questions: 25,
        difficulty: "Core",
        category: "Micro foundations",
      },
      {
        name: "Part II: Short Problems",
        questionType: "Short Answer",
        questions: 10,
        difficulty: "Core",
        category: "Regression diagnostics",
      },
      {
        name: "Part III: Essays",
        questionType: "Long Form",
        questions: 2,
        difficulty: "Applied",
        category: "Policy analysis",
      },
      {
        name: "Appendix: Data Interpretation",
        questionType: "Short Answer",
        questions: 5,
        difficulty: "Foundational",
        category: "Descriptive statistics",
      },
    ],
    generationSettings: [
      { label: "Questions to generate", value: "18" },
      {
        label: "Difficulty mix",
        value: "30% Easy · 50% Medium · 20% Hard",
      },
      {
        label: "Focus topics",
        value: "Instrumental variables · Time series",
      },
      { label: "Language", value: "English (UK)" },
    ],
  },
  {
    id: "format-template",
    name: "Blank University Cover Sheet",
    description: "Starter format with placeholder headings and empty sections.",
    savedAt: "1 week ago",
    status: "Template",
    layout: {
      headerLines: [
        "[Institution Name]",
        "[Faculty or Department]",
        "[Assessment Title]",
        "[Term / Academic Year]",
      ],
      metadata: [
        { label: "Course title", value: "[Course code]" },
        { label: "Lecturer", value: "[Instructor name]" },
        { label: "Date", value: "[DD Month YYYY]" },
        { label: "Duration", value: "[Exam duration]" },
      ],
      instructionIntro:
        "Use this template to define your institution-specific instructions:",
      instructions: [
        {
          text: "Replace placeholder text with institution-approved instructions.",
          emphasis: "normal",
        },
        {
          text: "List the materials candidates may bring into the exam room.",
          emphasis: "normal",
        },
      ],
      candidateFields: [
        "Name: _________________________________",
        "ID: _____________________",
      ],
      footerNotes: [],
    },
    sections: [
      {
        name: "Section placeholder",
        questionType: "Multiple Choice",
        questions: 10,
        difficulty: "Foundational",
        category: "[Topic]",
      },
      {
        name: "Section placeholder",
        questionType: "Short Answer",
        questions: 5,
        difficulty: "Core",
        category: "[Topic]",
      },
    ],
    generationSettings: [
      { label: "Questions to generate", value: "Custom" },
      { label: "Difficulty mix", value: "Define per section" },
      { label: "Bloom levels", value: "Define per section" },
      { label: "Language", value: "Configure in builder" },
    ],
  },
];

export const questionPresets: Record<string, BlueprintQuestion[]> = {
  "format-prototype": [
    // Section A: Multiple Choice (30 questions)
    {
      id: "q-proto-1",
      section: "Section A: Multiple Choice",
      prompt: "Which process best explains independent assortment during meiosis?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "Crossing over between non-sister chromatids in prophase I", correct: false },
        { label: "Random alignment of homologous chromosome pairs in metaphase I", correct: true },
        { label: "Separation of sister chromatids in anaphase II", correct: false },
        { label: "Cytokinesis at the end of meiosis II", correct: false },
      ],
      answer: "Random alignment of homologous chromosome pairs in metaphase I",
    },
    {
      id: "q-proto-2",
      section: "Section A: Multiple Choice",
      prompt: "Identify the stage where homologous chromosomes separate.",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "Prophase I", correct: false },
        { label: "Metaphase I", correct: false },
        { label: "Anaphase I", correct: true },
        { label: "Anaphase II", correct: false },
      ],
      answer: "Anaphase I",
    },
    {
      id: "q-proto-3",
      section: "Section A: Multiple Choice",
      prompt: "Which of the following best describes a gene?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "A segment of DNA that codes for a protein", correct: true },
        { label: "A complete chromosome", correct: false },
        { label: "A type of cell organelle", correct: false },
        { label: "A protein molecule", correct: false },
      ],
      answer: "A segment of DNA that codes for a protein",
    },
    {
      id: "q-proto-4",
      section: "Section A: Multiple Choice",
      prompt: "What is the primary function of DNA polymerase?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Breaking down DNA strands", correct: false },
        { label: "Synthesizing new DNA strands", correct: true },
        { label: "Unwinding the double helix", correct: false },
        { label: "Repairing damaged proteins", correct: false },
      ],
      answer: "Synthesizing new DNA strands",
    },
    {
      id: "q-proto-5",
      section: "Section A: Multiple Choice",
      prompt: "In which phase of the cell cycle does DNA replication occur?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "G1 phase", correct: false },
        { label: "S phase", correct: true },
        { label: "G2 phase", correct: false },
        { label: "M phase", correct: false },
      ],
      answer: "S phase",
    },
    {
      id: "q-proto-6",
      section: "Section A: Multiple Choice",
      prompt: "What is a genotype?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "The physical appearance of an organism", correct: false },
        { label: "The genetic makeup of an organism", correct: true },
        { label: "The environment affecting traits", correct: false },
        { label: "A mutation in DNA", correct: false },
      ],
      answer: "The genetic makeup of an organism",
    },
    {
      id: "q-proto-7",
      section: "Section A: Multiple Choice",
      prompt: "Which of the following is a purine base?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Thymine", correct: false },
        { label: "Cytosine", correct: false },
        { label: "Adenine", correct: true },
        { label: "Uracil", correct: false },
      ],
      answer: "Adenine",
    },
    {
      id: "q-proto-8",
      section: "Section A: Multiple Choice",
      prompt: "What is the complementary base to guanine in DNA?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "Adenine", correct: false },
        { label: "Thymine", correct: false },
        { label: "Cytosine", correct: true },
        { label: "Uracil", correct: false },
      ],
      answer: "Cytosine",
    },
    {
      id: "q-proto-9",
      section: "Section A: Multiple Choice",
      prompt: "Which process produces four haploid cells from one diploid cell?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "Mitosis", correct: false },
        { label: "Meiosis", correct: true },
        { label: "Binary fission", correct: false },
        { label: "Cytokinesis", correct: false },
      ],
      answer: "Meiosis",
    },
    {
      id: "q-proto-10",
      section: "Section A: Multiple Choice",
      prompt: "What is a dominant allele?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "An allele that is always expressed", correct: false },
        { label: "An allele that is expressed when present", correct: true },
        { label: "An allele that causes mutations", correct: false },
        { label: "An allele found only in males", correct: false },
      ],
      answer: "An allele that is expressed when present",
    },
    {
      id: "q-proto-11",
      section: "Section A: Multiple Choice",
      prompt: "Which enzyme unwinds the DNA double helix?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "DNA polymerase", correct: false },
        { label: "Helicase", correct: true },
        { label: "Ligase", correct: false },
        { label: "Primase", correct: false },
      ],
      answer: "Helicase",
    },
    {
      id: "q-proto-12",
      section: "Section A: Multiple Choice",
      prompt: "What is the result of a point mutation?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Change in a single nucleotide", correct: true },
        { label: "Deletion of an entire chromosome", correct: false },
        { label: "Duplication of genes", correct: false },
        { label: "Inversion of a DNA segment", correct: false },
      ],
      answer: "Change in a single nucleotide",
    },
    {
      id: "q-proto-13",
      section: "Section A: Multiple Choice",
      prompt: "What is nondisjunction?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Normal chromosome separation", correct: false },
        { label: "Failure of chromosomes to separate properly", correct: true },
        { label: "DNA replication error", correct: false },
        { label: "A type of gene mutation", correct: false },
      ],
      answer: "Failure of chromosomes to separate properly",
    },
    {
      id: "q-proto-14",
      section: "Section A: Multiple Choice",
      prompt: "Which of the following is true about RNA?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "It contains thymine", correct: false },
        { label: "It is double-stranded", correct: false },
        { label: "It contains uracil", correct: true },
        { label: "It cannot leave the nucleus", correct: false },
      ],
      answer: "It contains uracil",
    },
    {
      id: "q-proto-15",
      section: "Section A: Multiple Choice",
      prompt: "What is the function of messenger RNA?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Stores genetic information", correct: false },
        { label: "Carries amino acids to ribosomes", correct: false },
        { label: "Carries genetic information from DNA to ribosomes", correct: true },
        { label: "Forms the ribosome structure", correct: false },
      ],
      answer: "Carries genetic information from DNA to ribosomes",
    },
    {
      id: "q-proto-16",
      section: "Section A: Multiple Choice",
      prompt: "What is a codon?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "A three-nucleotide sequence that codes for an amino acid", correct: true },
        { label: "A single nucleotide in DNA", correct: false },
        { label: "A type of protein", correct: false },
        { label: "An enzyme that builds proteins", correct: false },
      ],
      answer: "A three-nucleotide sequence that codes for an amino acid",
    },
    {
      id: "q-proto-17",
      section: "Section A: Multiple Choice",
      prompt: "What is meant by the term 'phenotype'?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "The genetic code of an organism", correct: false },
        { label: "The observable characteristics of an organism", correct: true },
        { label: "The number of chromosomes", correct: false },
        { label: "The location of genes on chromosomes", correct: false },
      ],
      answer: "The observable characteristics of an organism",
    },
    {
      id: "q-proto-18",
      section: "Section A: Multiple Choice",
      prompt: "In a dihybrid cross, what is the expected phenotypic ratio in the F2 generation?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "3:1", correct: false },
        { label: "9:3:3:1", correct: true },
        { label: "1:2:1", correct: false },
        { label: "1:1:1:1", correct: false },
      ],
      answer: "9:3:3:1",
    },
    {
      id: "q-proto-19",
      section: "Section A: Multiple Choice",
      prompt: "What is the function of transfer RNA?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Carries genetic code from nucleus", correct: false },
        { label: "Brings amino acids to the ribosome", correct: true },
        { label: "Forms the ribosomal subunits", correct: false },
        { label: "Stores genetic information", correct: false },
      ],
      answer: "Brings amino acids to the ribosome",
    },
    {
      id: "q-proto-20",
      section: "Section A: Multiple Choice",
      prompt: "Which scientist is credited with discovering the structure of DNA?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "Gregor Mendel", correct: false },
        { label: "Watson and Crick", correct: true },
        { label: "Charles Darwin", correct: false },
        { label: "Louis Pasteur", correct: false },
      ],
      answer: "Watson and Crick",
    },
    {
      id: "q-proto-21",
      section: "Section A: Multiple Choice",
      prompt: "What is a chromosome?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "A single gene", correct: false },
        { label: "A condensed structure of DNA and proteins", correct: true },
        { label: "A type of RNA molecule", correct: false },
        { label: "A cellular organelle", correct: false },
      ],
      answer: "A condensed structure of DNA and proteins",
    },
    {
      id: "q-proto-22",
      section: "Section A: Multiple Choice",
      prompt: "What occurs during transcription?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "DNA is replicated", correct: false },
        { label: "RNA is synthesized from DNA", correct: true },
        { label: "Proteins are synthesized", correct: false },
        { label: "Amino acids are linked together", correct: false },
      ],
      answer: "RNA is synthesized from DNA",
    },
    {
      id: "q-proto-23",
      section: "Section A: Multiple Choice",
      prompt: "What is a recessive allele?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "An allele expressed only when homozygous", correct: true },
        { label: "An allele that is never expressed", correct: false },
        { label: "An allele found on the X chromosome", correct: false },
        { label: "An allele that causes disease", correct: false },
      ],
      answer: "An allele expressed only when homozygous",
    },
    {
      id: "q-proto-24",
      section: "Section A: Multiple Choice",
      prompt: "What is the role of ribosomes in protein synthesis?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "They store genetic information", correct: false },
        { label: "They are the site of protein synthesis", correct: true },
        { label: "They transport proteins out of the cell", correct: false },
        { label: "They replicate DNA", correct: false },
      ],
      answer: "They are the site of protein synthesis",
    },
    {
      id: "q-proto-25",
      section: "Section A: Multiple Choice",
      prompt: "What is the purpose of meiosis?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "To produce identical body cells", correct: false },
        { label: "To produce gametes for sexual reproduction", correct: true },
        { label: "To repair damaged tissue", correct: false },
        { label: "To increase cell size", correct: false },
      ],
      answer: "To produce gametes for sexual reproduction",
    },
    {
      id: "q-proto-26",
      section: "Section A: Multiple Choice",
      prompt: "What is an allele?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "A variant form of a gene", correct: true },
        { label: "A complete chromosome", correct: false },
        { label: "A type of protein", correct: false },
        { label: "A cell organelle", correct: false },
      ],
      answer: "A variant form of a gene",
    },
    {
      id: "q-proto-27",
      section: "Section A: Multiple Choice",
      prompt: "What is genetic linkage?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "Genes located close together on the same chromosome", correct: true },
        { label: "Genes located on different chromosomes", correct: false },
        { label: "Genes that code for the same trait", correct: false },
        { label: "Genes that mutate together", correct: false },
      ],
      answer: "Genes located close together on the same chromosome",
    },
    {
      id: "q-proto-28",
      section: "Section A: Multiple Choice",
      prompt: "What is the central dogma of molecular biology?",
      type: "Multiple Choice",
      difficulty: "Core",
      options: [
        { label: "DNA → RNA → Protein", correct: true },
        { label: "RNA → DNA → Protein", correct: false },
        { label: "Protein → RNA → DNA", correct: false },
        { label: "DNA → Protein → RNA", correct: false },
      ],
      answer: "DNA → RNA → Protein",
    },
    {
      id: "q-proto-29",
      section: "Section A: Multiple Choice",
      prompt: "What is a mutation?",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "A change in the DNA sequence", correct: true },
        { label: "Normal DNA replication", correct: false },
        { label: "A type of cell division", correct: false },
        { label: "A protein synthesis error", correct: false },
      ],
      answer: "A change in the DNA sequence",
    },
    {
      id: "q-proto-30",
      section: "Section A: Multiple Choice",
      prompt: "Identify one benefit of genetic recombination during meiosis.",
      type: "Multiple Choice",
      difficulty: "Foundational",
      options: [
        { label: "It reduces the chromosome number to haploid", correct: false },
        { label: "It produces identical daughter cells", correct: false },
        { label: "It increases allele variety among gametes", correct: true },
        { label: "It prevents all mutations", correct: false },
      ],
      answer: "It increases allele variety among gametes",
    },
    // Section B: Short Answers (15 questions)
    {
      id: "q-proto-31",
      section: "Section B: Short Answers",
      prompt: "Explain how crossing over increases genetic variation.",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Exchange of chromatid segments",
        "New allele combinations",
        "Prophase I",
      ],
    },
    {
      id: "q-proto-32",
      section: "Section B: Short Answers",
      prompt: "Describe one consequence of nondisjunction.",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Aneuploidy",
        "Trisomy or monosomy",
        "Improper chromosome separation",
      ],
    },
    {
      id: "q-proto-33",
      section: "Section B: Short Answers",
      prompt: "Define genotype and provide an example.",
      type: "Short Answer",
      difficulty: "Foundational",
      keywords: [
        "Genetic makeup",
        "Allele combination",
        "Example: AA, Aa, or aa",
      ],
    },
    {
      id: "q-proto-34",
      section: "Section B: Short Answers",
      prompt: "What is the difference between mitosis and meiosis?",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Mitosis produces 2 identical diploid cells",
        "Meiosis produces 4 haploid gametes",
        "Different purposes",
      ],
    },
    {
      id: "q-proto-35",
      section: "Section B: Short Answers",
      prompt: "Explain the role of DNA polymerase in replication.",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Synthesizes new DNA strands",
        "Adds nucleotides to 3' end",
        "Proofreading function",
      ],
    },
    {
      id: "q-proto-36",
      section: "Section B: Short Answers",
      prompt: "What is a point mutation and give an example?",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Single nucleotide change",
        "Substitution",
        "Example: sickle cell anemia",
      ],
    },
    {
      id: "q-proto-37",
      section: "Section B: Short Answers",
      prompt: "Describe the function of messenger RNA in protein synthesis.",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Carries genetic information",
        "From DNA to ribosome",
        "Template for translation",
      ],
    },
    {
      id: "q-proto-38",
      section: "Section B: Short Answers",
      prompt: "Explain what is meant by a recessive trait.",
      type: "Short Answer",
      difficulty: "Foundational",
      keywords: [
        "Expressed only when homozygous",
        "Two copies needed",
        "Masked by dominant allele",
      ],
    },
    {
      id: "q-proto-39",
      section: "Section B: Short Answers",
      prompt: "What is the significance of crossing over in meiosis?",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Increases genetic diversity",
        "Creates new allele combinations",
        "Occurs in prophase I",
      ],
    },
    {
      id: "q-proto-40",
      section: "Section B: Short Answers",
      prompt: "Describe the structure of DNA.",
      type: "Short Answer",
      difficulty: "Foundational",
      keywords: [
        "Double helix",
        "Sugar-phosphate backbone",
        "Complementary base pairs",
      ],
    },
    {
      id: "q-proto-41",
      section: "Section B: Short Answers",
      prompt: "What are the three main types of RNA and their functions?",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "mRNA carries genetic code",
        "tRNA brings amino acids",
        "rRNA forms ribosomes",
      ],
    },
    {
      id: "q-proto-42",
      section: "Section B: Short Answers",
      prompt: "Explain the concept of independent assortment.",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Random distribution of chromosomes",
        "Different gene combinations",
        "Occurs in metaphase I",
      ],
    },
    {
      id: "q-proto-43",
      section: "Section B: Short Answers",
      prompt: "What is the difference between transcription and translation?",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Transcription: DNA to RNA",
        "Translation: RNA to protein",
        "Different locations in cell",
      ],
    },
    {
      id: "q-proto-44",
      section: "Section B: Short Answers",
      prompt: "Describe how genes are inherited according to Mendel's law of segregation.",
      type: "Short Answer",
      difficulty: "Core",
      keywords: [
        "Alleles separate during gamete formation",
        "Each gamete receives one allele",
        "Random combination at fertilization",
      ],
    },
    {
      id: "q-proto-45",
      section: "Section B: Short Answers",
      prompt: "Explain what happens during the S phase of the cell cycle.",
      type: "Short Answer",
      difficulty: "Foundational",
      keywords: [
        "DNA replication",
        "Chromosome duplication",
        "Preparation for cell division",
      ],
    },
    // Section C: Essay (3 questions)
    {
      id: "q-proto-46",
      section: "Section C: Essay",
      prompt: "Compare and contrast meiosis I and meiosis II in terms of chromosome behavior.",
      type: "Long Form",
      difficulty: "Applied",
      keywords: [
        "Homologous vs sister chromatids",
        "Reductional vs equational division",
        "Genetic variation mechanisms",
      ],
    },
    {
      id: "q-proto-47",
      section: "Section C: Essay",
      prompt: "Discuss the role of mutations in evolution and provide specific examples.",
      type: "Long Form",
      difficulty: "Applied",
      keywords: [
        "Source of genetic variation",
        "Natural selection acts on mutations",
        "Beneficial, neutral, and harmful mutations",
        "Examples from nature",
      ],
    },
    {
      id: "q-proto-48",
      section: "Section C: Essay",
      prompt: "Explain the central dogma of molecular biology and describe how gene expression is regulated in eukaryotes.",
      type: "Long Form",
      difficulty: "Applied",
      keywords: [
        "DNA to RNA to protein flow",
        "Transcription factors",
        "Epigenetic modifications",
        "Post-transcriptional regulation",
        "Environmental influences",
      ],
    },
  ],
  "format-drafting": [
    {
      id: "q-draft-1",
      section: "Part I: Multiple Choice",
      prompt: "Which estimator is unbiased for the population mean given iid samples?",
      type: "Multiple Choice",
      difficulty: "Foundational",
    },
    {
      id: "q-draft-2",
      section: "Part II: Short Problems",
      prompt: "Compute the R-squared value for the provided regression output.",
      type: "Short Answer",
      difficulty: "Core",
    },
    {
      id: "q-draft-3",
      section: "Part III: Essays",
      prompt: "Evaluate the policy implications of simultaneous equations bias.",
      type: "Long Form",
      difficulty: "Applied",
    },
    {
      id: "q-draft-4",
      section: "Appendix: Data Interpretation",
      prompt: "Given the dataset, identify evidence of heteroskedasticity.",
      type: "Short Answer",
      difficulty: "Core",
    },
  ],
  "format-template": [
    {
      id: "q-template-1",
      section: "Section placeholder",
      prompt: "Replace this placeholder with a question from your bank.",
      type: "Multiple Choice",
      difficulty: "Foundational",
    },
    {
      id: "q-template-2",
      section: "Section placeholder",
      prompt: "Add another placeholder question here.",
      type: "Short Answer",
      difficulty: "Core",
    },
  ],
};
